env:
  ACCESS_TOKEN: d25ce86e4aff779111caec978910ff0a17a8e9cb
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
    - name: Vuepress to GitHub Pages
      uses: testthedocs/github-pages-deploy-action@0.0.2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: dist/
        BUILD_SCRIPT: npm install && npm run-script build
